server:
  port: 8080

spring:
  application:
    name: autocoleta
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    default-property-inclusion: non_empty
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 15000
            readTimeout: 120000
            loggerLevel: full
          salvarColeta:
            connectTimeout: 15000
            readTimeout: 120000
            loggerLevel: full
          adicionarOcorrencia:
            connectTimeout: 15000
            readTimeout: 120000
            loggerLevel: full
          authApi:
            connectTimeout: 15000
            readTimeout: 120000
            loggerLevel: full

logging:
  level:
    root: INFO
    com.tecnolog.autocoleta: DEBUG
    feign: DEBUG

app:
  scheduler:
    batch-size: 3
  dtm:
    view: "public.vw_dtm_pedidocoleta_unica"
    lock-table: "public.dtm_automation_lock"
  salvarColeta:
  #Homologação
    #baseUrl: "https://Hmg-beta.synclog.com.br"
    #tokenHash: "FF08C55E-9D84-4E09-A19C-920F66255E19"
  #Produção
    baseUrl: "https://beta.synclog.com.br"
    tokenHash: "FF08C55E-9D84-4E09-A19C-920F66255E19"
    timeout-seconds: 30
  salvarOcorrencia:
  #Homologação
    #baseUrl: "https://dev.synclog.com.br"
  #Produção
    baseUrl: "https://synclog.com.br"
    system-token: "5de61eb7-39a6-49e4-8b0c-a52e2659dc2e"
  defaults:
    hr-inicio: "08:00"         
    hr-fim: "16:00"            
