# ===================================================================
# ARQUIVO DE CONFIGURAÇÃO PARA O AMBIENTE DE PRODUÇÃO (prod)
# ===================================================================

spring:
  datasource:
    # ---- POSTGRES (PRIMÁRIO) - lido por @ConfigurationProperties("spring.datasource")
    jdbc-url: "jdbc:postgresql://localhost:5432/dtbSyncLog_Hmg"
    username: "postgres"
    password: "BRU*980192@no"
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PrimaryHikariPool
      maximum-pool-size: 20

    # ---- SQL SERVER (SECUNDÁRIO) - lido por @ConfigurationProperties("spring.datasource.sqlserver")
    sqlserver:
      jdbc-url: "jdbc:sqlserver://192.168.10.251:1433;databaseName=dtbTransporteHomologacao;encrypt=true;trustServerCertificate=true;"
      username: "sa"
      password: "esl@13509"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: SqlServerHikariPool
        maximum-pool-size: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Se você está configurando os DataSources manualmente via DataSourceConfig,
  # manter esses excludes evita que o Spring tente criar EntityManager/Hibernate sozinho:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
