spring:
  datasource:
    #Homologação Remota
    #jdbc-url: "jdbc:postgresql://10.58.16.3:5432/dtbSyncLog_Hmg"
    #Homologação Local
    #jdbc-url: "jdbc:postgresql://localhost:5432/dtbSyncLog_Hmg"
    #Produção Remota
    #jdbc-url: "jdbc:postgresql://10.58.16.3:5432/dtbSyncLog"
    #Produção Local
    jdbc-url: "jdbc:postgresql://localhost:5432/dtbSyncLog"
    username: "postgres"
    password: "BRU*980192@no"
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PrimaryHikariPool
      maximum-pool-size: 20

    sqlserver:
      #Homologação Local
      #jdbc-url: "jdbc:sqlserver://192.168.10.251:1433;databaseName=dtbTransporteHomologacao;encrypt=true;trustServerCertificate=true;"
      #Homologação Remota
      #jdbc-url: "jdbc:sqlserver://esl.tecnolog.com.br:1433;databaseName=dtbTransporteHomologacao;encrypt=true;trustServerCertificate=true;"
      #Produção Local
      jdbc-url: "jdbc:sqlserver://192.168.10.251:1433;databaseName=dtbTransporte;encrypt=true;trustServerCertificate=true;"
      #Produção Remota
      #jdbc-url: "jdbc:sqlserver://esl.tecnolog.com.br:1433;databaseName=dtbTransporte;encrypt=true;trustServerCertificate=true;"
      username: "sa"
      password: "esl@13509"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: SqlServerHikariPool
        maximum-pool-size: 20
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
